# Generated by Django 6.0.5 on 2026-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaiorder_chaireview_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chais/'),
        ),
    ]
